In [1]:
# API using requests
import requests

In [2]:
URL = "https://stephen-king-api.onrender.com/api/books"
res = requests.get(URL)
data  = res.json()

In [3]:
import pandas as pd
df = pd.json_normalize(data["data"])
df = df[['id','Title','Year','ISBN']]

In [4]:
df

    id            Title  Year                  ISBN
0    1           Carrie  1974     978-0-385-08695-0
1    2      Salem's Lot  1975     978-0-385-00751-1
2    3      The Shining  1977     978-0-385-12167-5
3    4             Rage  1977     978-0-451-07645-8
4    5        The Stand  1978     978-0-385-12168-2
..  ..              ...   ...                   ...
59  60        Elevation  2018     978-1-98210-231-9
60  61    The Institute  2019     978-1-98211-056-7
61  62            Later  2021     978-1-78909-649-1
62  63    Billy Summers  2021     978-1-982-17361-6
63  72  The Roopak Zone  1979  978-0-670-26069697-5

[64 rows x 4 columns]

In [8]:
# Web Scraping
import requests
URL= "https://www.scrapethissite.com/pages/simple/"
res = requests.get(URL)
print(res.status_code)

200

In [15]:
if res.status_code == 200:
    print(res.headers)
    # print(res.content)
with open ("scraped_data/data.html","w") as f:
    f.write(res.text)

{'Date': 'Sat, 29 Aug 2026 18:40:31 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=KyuTJFtB2DtWcu%2F7RvFGg0WyiqHQk2BQBN04MuR61zM%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1788028831"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=KyuTJFtB2DtWcu%2F7RvFGg0WyiqHQk2BQBN04MuR61zM%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1788028831"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': 'a32daf43abad797c-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

In [24]:
# Beautiful soup
!pip install beautifulsoup4
from bs4 import BeautifulSoup
with open("scraped_data/data.html","r") as f:
    html_content = f.read()
soup = BeautifulSoup(html_content,"lxml")

Requirement already satisfied: beautifulsoup4 in C:\Users\Saquib SK\AppData\Roaming\Python\Python314\site-packages (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\Saquib SK\AppData\Roaming\Python\Python314\site-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\Saquib SK\AppData\Roaming\Python\Python314\site-packages (from beautifulsoup4) (4.15.0)

In [46]:
soup.find("h1")
allh3 = soup.find_all("h3")
all_countries = []
type(allh3)
for h3 in allh3:
    name = (h3.get_text(strip = True))
    # print(h3.find_parent("div")["class"])
    population = (h3.find_next("div").select("span.country-population")[0].get_text(strip = True))
    all_countries.append([name,population])

In [62]:
import pandas as pd
df = pd.DataFrame(all_countries,columns = ["Name","Polpulation"])

In [63]:
df.to_csv("Cleaned_data/data.csv",index = False)

In [93]:
#Assignment problem - Activity
import requests
from bs4 import BeautifulSoup
i = 1
while True:
    URL = f"https://quotes.toscrape.com/page/{i}/"
    res = requests.get(URL)
    soup = BeautifulSoup(res.text,"lxml")
    quotes = soup.select("div.quote")
    if not quotes:
        print("No valid Pages anymore...")
        break
    with open(f"scraped_data/data{i}.html","w") as f:
        f.write(res.text)
        print(f"downloaded data from page{i}")
    i=i+1

downloaded data from page1
downloaded data from page2
downloaded data from page3
downloaded data from page4
downloaded data from page5
downloaded data from page6
downloaded data from page7
downloaded data from page8
downloaded data from page9
downloaded data from page10
No valid Pages anymore...

In [116]:
#Extrct Info
life_quotes = []
for i in range(1,11):
    with open(f"scraped_data/data{i}.html","r") as f:
        html_content = f.read()
    soup = BeautifulSoup(html_content,"lxml")
    all_quotes = soup.select("div.quote")
    # print(all_quotes)
    for q in all_quotes:
        all_tags = []
        for tag in q.select(".tags .tag"):
            all_tags.append(tag.get_text())
        # print(all_tags)
        if "life" in all_tags:
            text = q.select_one("span.text").get_text()
            # print(text)
            author = q.select_one("small.author").get_text()
            # print(author)
            life_quotes.append([text,author])
print(life_quotes)

[['“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”', 'Albert Einstein'], ['“It is better to be hated for what you are than to be loved for what you are not.”', 'André Gide'], ["“This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.”", 'Marilyn Monroe'], ['“I may not have gone where I intended to go, but I think I have ended up where I needed to be.”', 'Douglas Adams'], ['“Good friends, good books, and a sleepy conscience: this is the ideal life.”', 'Mark Twain'], ['“Life is what happens to us while we are making other plans.”', 'Allen Saunders'], ['“Today you are You, that is truer than true. There is no one alive who is Youer than You.”', 'Dr. Seuss'], ['“Life is like riding a bicycle. To keep your balance, you must keep moving.”', 'Albert Einstein'], ["“Life isn't about finding yourself. Life is about creating yourself.”", 'George Bernard Shaw'], ['“Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.”', 'Ralph Waldo Emerson'], ['“The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.”', 'Mark Twain'], ["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", 'Jimi Hendrix'], ['“But better to get hurt by the truth than comforted with a lie.”', 'Khaled Hosseini']]

In [117]:
import pandas as pd
pd.DataFrame(life_quotes,columns= ["Quotes","Authors"])

                                               Quotes              Authors
0   “There are only two ways to live your life. On...      Albert Einstein
1   “It is better to be hated for what you are tha...           André Gide
2   “This life is what you make it. No matter what...       Marilyn Monroe
3   “I may not have gone where I intended to go, b...        Douglas Adams
4   “Good friends, good books, and a sleepy consci...           Mark Twain
5   “Life is what happens to us while we are makin...       Allen Saunders
6   “Today you are You, that is truer than true. T...            Dr. Seuss
7   “Life is like riding a bicycle. To keep your b...      Albert Einstein
8   “Life isn't about finding yourself. Life is ab...  George Bernard Shaw
9   “Finish each day and be done with it. You have...  Ralph Waldo Emerson
10  “The fear of death follows from the fear of li...           Mark Twain
11  “I'm the one that's got to die when it's time ...         Jimi Hendrix
12  “But better to get hurt by the truth than comf...      Khaled Hosseini